[package]
name = "archivist_compress"
version = "0.2.1"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
license = "MIT"
build = "build.rs"

[dependencies]
bzip2 = "0.3.3"
clap = "2.33.0"
flate2 = "1.0.11"
xz2 = "0.1.6"
