[package]
name = "archivist_compress"
version = "0.2.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
license = "MIT"
build = "build.rs"

[dependencies]
bzip2 = "0.3"
clap = "2"
flate2 = "1"
xz2 = "0.1"