name: Tests
on: [push, pull_request]
jobs:
  test-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        host: [x86_64, i686]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        rust-channel: stable
        rust-host: ${{ matrix.host }}
        cache: false
    - name: Run tests
      run: cargo test --all
  test-nightly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        rust-channel: nightly
        cache: false
    - name: Run tests
      run: cargo test --all
  test-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu, arm-unknown-linux-gnueabi, armv7-unknown-linux-gnueabihf]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        rust-target: ${{ matrix.target }}
        install-cross: true
        cache: false
    - name: Run tests
      run: cross test --all --target ${{ matrix.target }}