name: Tests
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        cache: false
    - name: Run tests
      run: cargo test --all
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        host: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        rust-channel: stable
        rust-host: ${{ matrix.host }}
        cache: false
    - name: Run tests
      run: cargo test --all
  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        cache: false
    - name: Run tests
      run: cargo test --all
  cross-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [i686-unknown-linux-gnu, aarch64-unknown-linux-gnu, arm-unknown-linux-gnueabi, armv7-unknown-linux-gnueabihf]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        rust-target: ${{ matrix.target }}
        install-cross: true
        cache: false
    - name: Run tests
      run: cross test --all --target ${{ matrix.target }}
  cross-macos:
    runs-on: macOS-latest
    strategy:
      matrix:
        target: [i686-apple-darwin]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        rust-target: ${{ matrix.target }}
        install-cross: true
        cache: false
    - name: Run tests
      run: cross test --all --target ${{ matrix.target }}